name: stupidwebauthnexample
services:
  mail:
    image: axllent/mailpit
    ports:
      - 127.0.0.1:8025:8025
      # - 127.0.0.1:8125:1025
    environment:
      - "MP_SMTP_AUTH_ACCEPT_ANY=true"
      - "MP_SMTP_AUTH_ALLOW_INSECURE=true"
  auth:
    image: ghcr.io/stupidwebauthn/server:v1.8.2
    restart: unless-stopped
    depends_on:
      - mail
    environment:
      - SMTP_HOST=mail
      - SMTP_PORT=1025
      - SMTP_SECURE=false
      - SMTP_USERNAME=user@example.com
      - SMTP_PASSWORD=password
      - SMTP_FROM=user@example.com
      - EMAIL_VALIDATION_URL=http://localhost:5178/register
      - WEBAUTHN_ORIGIN=http://localhost:5178
      - COOKIE_DOMAIN=localhost
      - COOKIE_SECURE=false
      - COOKIE_SECRET=zH4NRP1HMALxxCFnRZABFA7GOJtzU_gIj02alfL1lvI
      - DATABASE_PATH=./data/db.sqlite
      - EMAIL_TEMPLATE_PATH=data/email.html
      - PORT=80
    volumes:
      - ./data:/app/data
  example_backend:
    build:
      context: backend
    # ports:
    #   - 127.0.0.1:5179:5179
    depends_on:
      - auth
    environment:
      - SWA_BASE=http://auth:80
      - PORT=80
  example_frontend:
    build:
      context: frontend
    depends_on:
      - example_backend
    ports:
      - 127.0.0.1:5178:80
